--CREAR DATABASE DE LO PRINCIPAL
CREATE DATABASE LOGINDBS
GO

--CREAR TABLA USUARIO
CREATE TABLE USUARIOS
(
	ID INT PRIMARY KEY IDENTITY,
	Usuario NVARCHAR(50) NOT NULL,
	Contraseña NVARCHAR(50) NOT NULL,

);
--CREAR TABLA ROL
CREATE TABLE ROLES
(
    IDR INT PRIMARY KEY IDENTITY,
    NOMBREROL VARCHAR(50) NOT NULL
)

--INSERTAR VALORES A LOS USUARIOS
INSERT INTO USUARIOS (Usuario, Contraseña)
VALUES ('tito','1234')
INSERT INTO USUARIOS (Usuario, Contraseña)
VALUES ('ADMIN','ADMIN')
INSERT INTO USUARIOS (Usuario, Contraseña)
VALUES ('alan','1111')
INSERT INTO USUARIOS (Usuario, Contraseña)
VALUES ('JUAN','JUAN')
INSERT INTO USUARIOS (Usuario, Contraseña)
VALUES ('PABLO','2222')


--INSERTAR ROLES

--USUARIO
INSERT INTO ROLES (NOMBREROL)
VALUES ('Usuario')
--ADMIN

INSERT INTO ROLES (NOMBREROL)
VALUES ('ADMIN')

--INVITADO
INSERT INTO ROLES (NOMBREROL)
VALUES ('INVITADO')

ALTER TABLE Usuarios
ADD IDR INT


--ALTERNAR TABLAS
ALTER TABLE Usuarios
ADD CONSTRAINT FK_Usuarios_Roles FOREIGN KEY (IDR) REFERENCES Roles(IDR)

UPDATE Usuarios SET IDR = 2 WHERE Usuario = 'ADMIN'
UPDATE Usuarios SET IDR = 1 WHERE Usuario = 'tito'
UPDATE Usuarios SET IDR = 3 WHERE Usuario = 'Alan'
UPDATE Usuarios SET IDR = 3 WHERE Usuario = 'JUAN'
UPDATE Usuarios SET IDR = 2 WHERE Usuario = 'PABLO'



